apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $index, $port := .Values.containerPorts }}
    - port: {{ required "Missing required ports[].containerPort entry" $port.containerPort }}
      targetPort: {{  required "Missing required ports[].name entry" $port.name | lower }}
      protocol: {{ default "TCP" $port.protocol }}
      name: {{  required "Missing required ports[].name entry" $port.name | lower }}
    {{- end }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
