spring:
  main:
    allow-circular-references: true
  application:
    name: ecohack-template
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?createDatabaseIfNotExist=true
    username: usr_application
    password: usr_password

app:
  jwt:
    # Signing key for HS512 algorithm
    # In http://www.allkeysgenerator.com/ you can generate all kinds of keys
    secret: geekSquad1617478ibsdcfidsbvnsdvbnvuinyvbnkbfisdigvbnsdvnfvusdbncdsuvsdnvbdsvdsuibyuvbsdfuy
    expiration:
      minutes: 10
  cors:
    allowed-origins: "*"

logging:
  level:
    org.springframework.security: DEBUG
    # org.hibernate.SQL: DEBUG
